# Lab 04-2

## Loading data from file

In [1]:
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [3]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 Cost:  6355.4985 
Prediction:
 [[ 74.647156]
 [ 94.915955]
 [ 90.91693 ]
 [100.73115 ]
 [ 71.792   ]
 [ 55.247555]]
10 Cost:  5.951161 
Prediction:
 [[148.9432 ]
 [184.22842]
 [178.91054]
 [196.55609]
 [139.91672]
 [105.46446]]
20 Cost:  5.644066 
Prediction:
 [[149.45332]
 [184.83015]
 [179.5095 ]
 [197.2061 ]
 [140.37471]
 [105.7972 ]]
30 Cost:  5.628247 
Prediction:
 [[149.46371 ]
 [184.8311  ]
 [179.51657 ]
 [197.2115  ]
 [140.37445 ]
 [105.792114]]
40 Cost:  5.6125646 
Prediction:
 [[149.47069]
 [184.828  ]
 [179.51962]
 [197.21255]
 [140.3711 ]
 [105.78477]]
50 Cost:  5.596983 
Prediction:
 [[149.47763 ]
 [184.82486 ]
 [179.52263 ]
 [197.21358 ]
 [140.36772 ]
 [105.777435]]
60 Cost:  5.581444 
Prediction:
 [[149.48454]
 [184.82176]
 [179.52567]
 [197.21458]
 [140.3644 ]
 [105.77011]]
70 Cost:  5.5660534 
Pr

960 Cost:  4.4850173 
Prediction:
 [[150.02235]
 [184.5822 ]
 [179.7619 ]
 [197.28355]
 [140.11623]
 [105.19186]]
970 Cost:  4.4755883 
Prediction:
 [[150.02747]
 [184.57993]
 [179.76416]
 [197.28409]
 [140.11398]
 [105.18624]]
980 Cost:  4.4661813 
Prediction:
 [[150.0326 ]
 [184.5777 ]
 [179.76645]
 [197.28465]
 [140.11179]
 [105.18065]]
990 Cost:  4.4568176 
Prediction:
 [[150.03769 ]
 [184.57547 ]
 [179.7687  ]
 [197.28519 ]
 [140.10959 ]
 [105.175064]]
1000 Cost:  4.4475155 
Prediction:
 [[150.04279]
 [184.57324]
 [179.77098]
 [197.28574]
 [140.10739]
 [105.1695 ]]
1010 Cost:  4.4382577 
Prediction:
 [[150.04782]
 [184.57101]
 [179.77322]
 [197.28625]
 [140.10522]
 [105.16395]]
1020 Cost:  4.429065 
Prediction:
 [[150.05286]
 [184.56879]
 [179.77545]
 [197.28677]
 [140.10303]
 [105.15841]]
1030 Cost:  4.4198823 
Prediction:
 [[150.0579  ]
 [184.56657 ]
 [179.7777  ]
 [197.28731 ]
 [140.10088 ]
 [105.152885]]
1040 Cost:  4.410803 
Prediction:
 [[150.06291]
 [184.56438]
 [179.77992]

1770 Cost:  3.8539398 
Prediction:
 [[150.38815 ]
 [184.42377 ]
 [179.92627 ]
 [197.31578 ]
 [139.96738 ]
 [104.784874]]
1780 Cost:  3.8475552 
Prediction:
 [[150.3921 ]
 [184.42207]
 [179.92805]
 [197.31602]
 [139.9659 ]
 [104.78039]]
1790 Cost:  3.8412287 
Prediction:
 [[150.39604]
 [184.42043]
 [179.92986]
 [197.31628]
 [139.96443]
 [104.77594]]
1800 Cost:  3.8349297 
Prediction:
 [[150.39995 ]
 [184.41875 ]
 [179.93164 ]
 [197.31654 ]
 [139.96297 ]
 [104.771484]]
1810 Cost:  3.828656 
Prediction:
 [[150.40384]
 [184.41708]
 [179.93341]
 [197.31677]
 [139.96152]
 [104.76705]]
1820 Cost:  3.8224165 
Prediction:
 [[150.40775]
 [184.41544]
 [179.9352 ]
 [197.31703]
 [139.96008]
 [104.76264]]
1830 Cost:  3.816185 
Prediction:
 [[150.41162 ]
 [184.41379 ]
 [179.93695 ]
 [197.31726 ]
 [139.95865 ]
 [104.758224]]
1840 Cost:  3.810023 
Prediction:
 [[150.41547]
 [184.41214]
 [179.9387 ]
 [197.31749]
 [139.9572 ]
 [104.75383]]
1850 Cost:  3.8038375 
Prediction:
 [[150.41934]
 [184.41052]
 [1

## Queue Runner
참조: [https://www.tensorflow.org/programmers_guide/datasets](https://www.tensorflow.org/programmers_guide/datasets)

크기가 큰 파일들을 미리 다 메모리에 올려놓지 않고 queue를 이용해 필요할 때 꺼내쓸 수 있도록 도와준다.

In [6]:
# 1. 파일 이름을 갖고있는 Filename Queue를 만든다.
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')

# 2. Filename Queue로부터 파일을 읽는 Reader를 만든다.
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# 3. 읽은 파일 내용을 복호화한다.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

## tf.train.batch
여러 row를 batch_size만큼씩 쪼개어 이용할 수 있게 도와준다.

In [ ]:
# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

sess = tf.Session()
...

# Start populating the filename queue.
coord = tf.train.Coordinator()
thread = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    ...
    
coord.request_stop()
coord.join(threads)

In [9]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
thread = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)
        
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, data-01-test-score.scv; No such file or directory
	 [[Node: ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](TextLineReaderV2_1, filename_queue_1)]]
	 [[Node: DecodeCSV_1/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_10_DecodeCSV_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


OutOfRangeError: FIFOQueue '_18_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]

Caused by op 'batch_2', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-cac442e78f91>", line 11, in <module>
    train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 927, in batch
    name=name)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 722, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py", line 464, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2418, in _queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/jinhyuk/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_18_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]
