# Lab 08

## Simple ID array and slicing

In [1]:
import numpy as np

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2D Array

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

print(t.ndim) # rank
print(t.shape) # shape

2
(4, 3)


## Shape, Rank, Axis

In [8]:
import tensorflow as tf

/home/jinhyuk/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [12]:
t = tf.constant([1, 2, 3, 4])

with tf.Session() as sess:
    print(tf.shape(t).eval())

[4]


In [14]:
t = tf.constant([[1, 2], [3, 4]])

with tf.Session() as sess:
    print(tf.shape(t).eval())

[2 2]


In [16]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])

with tf.Session() as sess:
    print(tf.shape(t).eval())

[1 2 3 4]


## Matmul vs. multiply

In [21]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)

with tf.Session() as sess:
    print(tf.matmul(matrix1, matrix2).eval())

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)
[[ 5.]
 [11.]]


## Broadcasting

In [24]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])

with tf.Session() as sess:
    print((matrix1 + matrix2).eval())

[[5. 5.]]


In [26]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)

with tf.Session() as sess:
    print((matrix1 + matrix2).eval())

[[4. 5.]]


In [28]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])

with tf.Session() as sess:
    print((matrix1 + matrix2).eval())

[[4. 6.]]


In [29]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])

with tf.Session() as sess:
    print((matrix1 + matrix2).eval())

[[4. 5.]
 [5. 6.]]


## Reduce mean

In [30]:
with tf.Session() as sess:
    print(tf.reduce_mean([1, 2], axis=0).eval())

1


In [31]:
x = [[1., 2.], [3., 4.]]

with tf.Session() as sess:
    print(tf.reduce_mean(x).eval())

2.5


In [32]:
with tf.Session() as sess:
    print(tf.reduce_mean(x, axis=0).eval())

[2. 3.]


In [33]:
with tf.Session() as sess:
    print(tf.reduce_mean(x, axis=1).eval())

[1.5 3.5]


In [34]:
with tf.Session() as sess:
    print(tf.reduce_mean(x, axis=-1).eval())

[1.5 3.5]


## Reduce sum

In [35]:
x = [[1., 2.], [3., 4.]]

with tf.Session() as sess:
    print(tf.reduce_sum(x).eval())

10.0


In [39]:
with tf.Session() as sess:
    print(tf.reduce_sum(x, axis=0).eval())

[4. 6.]


In [41]:
with tf.Session() as sess:
    print(tf.reduce_sum(x, axis=-1).eval())

[3. 7.]


In [40]:
with tf.Session() as sess:
    print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval())

5.0


## Argmax

In [42]:
x = [[0, 1, 2], [2, 1, 0]]

with tf.Session() as sess:
    print(tf.argmax(x, axis=0).eval())

[1 0 0]


In [43]:
with tf.Session() as sess:
    print(tf.argmax(x, axis=1).eval())

[2 0]


In [44]:
with tf.Session() as sess:
    print(tf.argmax(x, axis=-1).eval())

[2 0]


## Reshape

In [45]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

print(t.shape)

(2, 2, 3)


In [48]:
with tf.Session() as sess:
    print(tf.reshape(t, shape=[-1, 3]).eval())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [49]:
with tf.Session() as sess:
    print(tf.reshape(t, shape=[-1, 1, 3]).eval())

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


## Reshape (squeeze, expand)

In [50]:
with tf.Session() as sess:
    print(tf.squeeze([[0], [1], [2]]).eval())

[0 1 2]


In [51]:
with tf.Session() as sess:
    print(tf.expand_dims([0, 1, 2], 1).eval())

[[0]
 [1]
 [2]]


## One hot

In [52]:
with tf.Session() as sess:
    print(tf.one_hot([[0], [1], [2], [0]], depth=3).eval())

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]


In [53]:
with tf.Session() as sess:
    t = tf.one_hot([[0], [1], [2], [0]], depth=3)
    print(tf.reshape(t, shape=[-1, 3]).eval())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## Casting

In [54]:
with tf.Session() as sess:
    print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval())

[1 2 3 4]


In [55]:
with tf.Session() as sess:
    print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval())

[1 0 1 0]


## Stack

In [58]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

with tf.Session() as sess:
    print(tf.stack([x, y, z]).eval())

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [57]:
with tf.Session() as sess:
    print(tf.stack([x, y, z], axis=1).eval())

[[1 2 3]
 [4 5 6]]


## Ones and Zeros like

In [60]:
x = [[0, 1, 2],
     [2, 1, 0]]

with tf.Session() as sess:
    print(tf.ones_like(x).eval())

[[1 1 1]
 [1 1 1]]


In [61]:
with tf.Session() as sess:
    print(tf.zeros_like(x).eval())

[[0 0 0]
 [0 0 0]]


## Zip

In [62]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [63]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
