# Lab 12-5

## Dynamic RNN

In [6]:
import numpy as np
import tensorflow as tf

h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, sequence_length=[5, 3, 4], dtype=tf.float32)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(outputs.eval())

[[[-0.11812627  0.09363966]
  [-0.10858143  0.09203401]
  [ 0.04059173 -0.11115704]
  [ 0.1820537  -0.23387417]
  [ 0.26986024 -0.11708424]]

 [[-0.02544947  0.01201867]
  [ 0.10617413  0.0118539 ]
  [ 0.23107281 -0.13272998]
  [ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.15715177 -0.15633716]
  [ 0.2560509  -0.25263852]
  [ 0.11674368 -0.27546832]
  [ 0.06328122 -0.22367266]
  [ 0.          0.        ]]]
