# Lab 12-1

In [1]:
import numpy as np
import tensorflow as tf
import pprint as pp

/home/jinhyuk/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## RNN in TensorFlow

1. create a cell
```python
cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
```

2. create outputs
```python
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
```

## One node: 4 (input-dim) in 2 (hidden_size)

In [10]:
hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[[1, 0, 0, 0]]], dtype=np.float32)
with tf.variable_scope('rnn', reuse=tf.AUTO_REUSE) as scope:
    outputs, _ = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32, scope=scope)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[0.05512083, 0.04178677]]], dtype=float32)


## Unfolding to n sequences

In [12]:
# hidden_size=2, sequence_length=5
# sequence_length is a number of unfolded cells and it automatically defined by dimension of input data

h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
with tf.variable_scope('rnn', reuse=tf.AUTO_REUSE) as scope:
    outputs, _ = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32, scope=scope)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 0.01205457, -0.06495225],
        [-0.05564936, -0.04058176],
        [ 0.0488038 ,  0.0676472 ],
        [ 0.13734378,  0.13817015],
        [ 0.31254596,  0.01980137]]], dtype=float32)


## Batching input

In [13]:
# hidden_size=2, sequence_length=5, batch_size=3
# batch size is a number of data

h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)
with tf.variable_scope('rnn', reuse=tf.AUTO_REUSE) as scope:
    outputs, _ = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32, scope=scope)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[-0.14534512,  0.00050378],
        [-0.09984852,  0.0238088 ],
        [-0.01223521, -0.10729959],
        [ 0.03769117, -0.21433607],
        [-0.01439657, -0.05820508]],

       [[-0.02419695,  0.00396508],
        [-0.04170949,  0.07611369],
        [ 0.04421178, -0.05545608],
        [ 0.07837626, -0.18496408],
        [ 0.08536024, -0.2788304 ]],

       [[ 0.05746493, -0.13791747],
        [ 0.07750098, -0.24467468],
        [-0.01709338, -0.17768921],
        [-0.06927705, -0.10108864],
        [-0.00557331, -0.19262384]]], dtype=float32)
