# Lab 04

## Hypothesis using matrix
$H(x_{1}, x_{2}, x_{3}) = x_{1}w_{1} + x_{2}w_{2} + x_{3}w_{3}$

In [5]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90, 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  37116.5 
Prediction:
 [-12.678286 -25.57095  -19.875698 -20.553417 -23.159796]
10 Cost:  31.872461 
Prediction:
 [157.65504 179.19661 181.86473 199.13853 133.03474]
20 Cost:  31.371622 
Prediction:
 [158.14957 179.83054 182.46881 199.7981  133.52669]
30 Cost:  31.211155 
Prediction:
 [158.13026 179.84674 182.46434 199.7949  133.54747]
40 Cost:  31.051544 
Prediction:
 [158.10947 179.86105 182.45804 199.78973 133.56677]
50 Cost:  30.892834 
Prediction:
 [158.08873 179.87532 182.45177 199.78459 133.58603]
60 Cost:  30.734955 
Prediction:
 [158.06805 179.88957 182.44551 199.77945 133.60522]
70 Cost:  30.577845 
Prediction:
 [158.04742 179.90378 182.43927 199.77432 133.62439]
80 Cost:  30.421606 
Prediction:
 [158.02687 179.91795 182.43306 199.76921 133.64351]
90 Cost:  30.266296 
Prediction:
 [158.00635 179.93207 182.42685 199.7641  133.66254]
100 Cost:  30.111805 
Prediction:
 [157.9859  179.94615 182.42067 199.759   133.68153]
110 Cost:  29.958044 
Prediction:
 [157.9655  179.9

1050 Cost:  18.654377 
Prediction:
 [156.27791 181.12288 181.90472 199.32825 135.27437]
1060 Cost:  18.562277 
Prediction:
 [156.2622  181.1337  181.9     199.32422 135.2891 ]
1070 Cost:  18.470661 
Prediction:
 [156.24654 181.1445  181.89526 199.32019 135.30376]
1080 Cost:  18.379513 
Prediction:
 [156.23091 181.15526 181.89055 199.31618 135.3184 ]
1090 Cost:  18.288849 
Prediction:
 [156.21533 181.16602 181.88583 199.3122  135.33301]
1100 Cost:  18.198647 
Prediction:
 [156.19978 181.17673 181.88116 199.3082  135.34758]
1110 Cost:  18.109037 
Prediction:
 [156.1843  181.18741 181.8765  199.30423 135.36209]
1120 Cost:  18.019796 
Prediction:
 [156.16884 181.19807 181.87184 199.30026 135.37659]
1130 Cost:  17.931072 
Prediction:
 [156.15344 181.20871 181.8672  199.29633 135.39105]
1140 Cost:  17.842855 
Prediction:
 [156.13806 181.21928 181.86255 199.29236 135.40544]
1150 Cost:  17.755058 
Prediction:
 [156.12273 181.22984 181.85793 199.2884  135.41982]
1160 Cost:  17.667805 
Predictio

## Matrix
$$
\begin{pmatrix} 
x_{1} & x_{2} & x_{3}
\end{pmatrix}
\cdot
\begin{pmatrix} 
w_{1} \\
w_{2} \\
w_{3}
\end{pmatrix}
=
\begin{pmatrix} 
x_{1}w_{1} + x_{2}w_{2} + x_{3}w_{3}
\end{pmatrix}
$$

In [8]:
import tensorflow as tf

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]] # [5, 3]
y_data = [[152.], [185.], [180.], [196.], [142.]] # [5, 1]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  130152.29 
Prediction:
 [[-163.35965]
 [-203.32864]
 [-196.33656]
 [-218.69289]
 [-152.80699]]
10 Cost:  10.812202 
Prediction:
 [[155.75803]
 [180.24623]
 [181.59624]
 [192.86847]
 [139.76718]]
20 Cost:  9.58457 
Prediction:
 [[156.71336]
 [181.41373]
 [182.73651]
 [194.11221]
 [140.6608 ]]
30 Cost:  9.548579 
Prediction:
 [[156.70609]
 [181.42413]
 [182.73672]
 [194.11447]
 [140.67186]]
40 Cost:  9.512741 
Prediction:
 [[156.6959 ]
 [181.43106]
 [182.73352]
 [194.11299]
 [140.68019]]
50 Cost:  9.47714 
Prediction:
 [[156.68575]
 [181.43793]
 [182.73033]
 [194.1115 ]
 [140.68852]]
60 Cost:  9.441656 
Prediction:
 [[156.67561]
 [181.44481]
 [182.7271 ]
 [194.10997]
 [140.69682]]
70 Cost:  9.406397 
Prediction:
 [[156.66551]
 [181.45164]
 [182.72389]
 [194.10847]
 [140.70512]]
80 Cost:  9.371367 
Prediction:
 [[156.65546]
 [181.45845]
 [182.72069]
 [194.10701]
 [140.71336]]
90 Cost:  9.336539 
Prediction:
 [[156.64542]
 [181.46524]
 [182.71753]
 [194.10553]
 [140.7216 ]]
100 Co

940 Cost:  6.9444666 
Prediction:
 [[155.88057]
 [181.98256]
 [182.47415]
 [193.99901]
 [141.34184]]
950 Cost:  6.9221163 
Prediction:
 [[155.87254]
 [181.98798]
 [182.4716 ]
 [193.99797]
 [141.34827]]
960 Cost:  6.8998322 
Prediction:
 [[155.86452]
 [181.9934 ]
 [182.46904]
 [193.9969 ]
 [141.35469]]
970 Cost:  6.877675 
Prediction:
 [[155.85654]
 [181.99878]
 [182.46649]
 [193.99591]
 [141.36108]]
980 Cost:  6.855645 
Prediction:
 [[155.84859]
 [182.00417]
 [182.46393]
 [193.99487]
 [141.36746]]
990 Cost:  6.8336935 
Prediction:
 [[155.8406 ]
 [182.00952]
 [182.46136]
 [193.9938 ]
 [141.37381]]
1000 Cost:  6.8119035 
Prediction:
 [[155.83269]
 [182.01488]
 [182.45886]
 [193.9928 ]
 [141.38016]]
1010 Cost:  6.790258 
Prediction:
 [[155.82481]
 [182.02022]
 [182.45636]
 [193.99179]
 [141.3865 ]]
1020 Cost:  6.768645 
Prediction:
 [[155.81693]
 [182.02554]
 [182.45384]
 [193.9908 ]
 [141.3928 ]]
1030 Cost:  6.7471414 
Prediction:
 [[155.80905]
 [182.03085]
 [182.45131]
 [193.98978]
 [14

1870 Cost:  5.2808557 
Prediction:
 [[155.2161 ]
 [182.43057]
 [182.26093]
 [193.91924]
 [141.867  ]]
1880 Cost:  5.266841 
Prediction:
 [[155.20976]
 [182.43481]
 [182.2589 ]
 [193.91855]
 [141.87193]]
1890 Cost:  5.2529087 
Prediction:
 [[155.20348]
 [182.43906]
 [182.25687]
 [193.91788]
 [141.87683]]
1900 Cost:  5.239037 
Prediction:
 [[155.1972 ]
 [182.44327]
 [182.25482]
 [193.91722]
 [141.88168]]
1910 Cost:  5.2252584 
Prediction:
 [[155.19092]
 [182.44748]
 [182.2528 ]
 [193.9165 ]
 [141.88654]]
1920 Cost:  5.2114897 
Prediction:
 [[155.18466]
 [182.45168]
 [182.25076]
 [193.91585]
 [141.89139]]
1930 Cost:  5.1978054 
Prediction:
 [[155.17844]
 [182.4559 ]
 [182.24878]
 [193.9152 ]
 [141.89624]]
1940 Cost:  5.1842375 
Prediction:
 [[155.17224]
 [182.4601 ]
 [182.24678]
 [193.91454]
 [141.90108]]
1950 Cost:  5.170689 
Prediction:
 [[155.16603]
 [182.46426]
 [182.24478]
 [193.9139 ]
 [141.9059 ]]
1960 Cost:  5.157245 
Prediction:
 [[155.15984]
 [182.46843]
 [182.24278]
 [193.9132 